"""feature 002: tabla checkin_device_locks y razon_denegacion

Revision ID: e8bdfb173fb7
Revises: adc852f8fca8
Create Date: 2026-07-09 14:34:57.391523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bdfb173fb7'
down_revision = 'adc852f8fca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_device_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_device_locks_device_id'), 'checkin_device_locks', ['device_id'], unique=True)
    op.create_index(op.f('ix_checkin_device_locks_id'), 'checkin_device_locks', ['id'], unique=False)
    # NOTA: autogenerate detectó como "removido" el índice único parcial
    # ix_checkins_usuario_dia_activo de 001 (creado con SQL crudo, Alembic no
    # lo reconoce como metadata ORM) y proponía un DROP INDEX — se quita a
    # mano, ese índice sigue vigente y no lo toca esta migración.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_device_locks_id'), table_name='checkin_device_locks')
    op.drop_index(op.f('ix_checkin_device_locks_device_id'), table_name='checkin_device_locks')
    op.drop_table('checkin_device_locks')
    # ### end Alembic commands ###
